controllers:
    resource: ../../src/Controller/
    type: annotation

api:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api

admin:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /admin


kernel:
    resource: ../../src/Kernel.php
    type: annotation
